microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-platform-authorizer
    tag: "0.2.9-9-PIDM-484-update-helm-chart"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 3
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 8080
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 8080
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuprod.shared.internal.platform.pagopa.it"
    path: /authorizer-functions/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "shared-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "756Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  fileConfig: {}
  envConfig:
    WEBSITE_SITE_NAME: "pagopa-p-shared-authorizer" # required to show cloud role name in application insights # TODO
    FUNCTIONS_WORKER_RUNTIME: "java"
    RETRY_NUMBER: "4"
    STARTING_RETRY_DELAY_MILLIS: "1500"
    ASPNETCORE_URLS: "http://*:8080"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    COSMOS_CONN_STRING: 'auth-p-cosmos-connection-string'
    REFRESH_CONFIGURATION_PATH: 'auth-p-refresh-configuration-url'
    APICONFIG_SELFCARE_INTEGRATION_PATH: 'auth-p-apiconfig-selfcare-integration-url'
    APICONFIG_SELFCARE_INTEGRATION_SUBKEY: 'auth-p-apiconfig-selfcare-integration-subkey'
  keyvault:
    name: "pagopa-p-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - "user"
  canaryDelivery:
    create: false
    deployment:
      create: false
      image:
        repository: ghcr.io/pagopa/pagopa-platform-authorizer
        tag: "0.2.3"
  create: false
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
